#pragma once
#define SDL_MAIN_HANDLED

#define BOARD_MIN_DIMENSION 9


#define GAME_OVER_POPUP_WIDTH 7
#define GAME_OVER_POPUP_HEIGHT 5

//Text
#define TEXT_SIZE 32

#define TEXT_GAME_OVER_WIDTH 5
#define TEXT_GAME_OVER_HEIGHT 1

#define TEXT_GAME_RESULT_WIDTH 2
#define TEXT_GAME_RESULT_HEIGHT 1


#define TEXT_PLAY_AGAIN_WIDTH 3
#define TEXT_PLAY_AGAIN_HEIGHT 1


#define YES_BUTTON_WIDTH 1
#define YES_BUTTON_HEIGHT 1


#define NO_BUTTON_WIDTH 1
#define NO_BUTTON_HEIGHT 1


