#pragma once
#define SDL_MAIN_HANDLED

#define TABLE_ROW 10
#define TABLE_COL 15
#define TABLE_SIZE (TABLE_ROW * TABLE_COL)
#define TABLE_CELL_SIZE 40

#define WINDOW_WIDTH (TABLE_CELL_SIZE * TABLE_COL)
#define WINDOW_HEIGHT (TABLE_CELL_SIZE * TABLE_ROW)

#define GAME_OVER_POPUP_WIDTH 280
#define GAME_OVER_POPUP_HEIGHT 200
#define GAME_OVER_POPUP_X ((WINDOW_WIDTH - GAME_OVER_POPUP_WIDTH) / 2)
#define GAME_OVER_POPUP_Y ((WINDOW_HEIGHT - GAME_OVER_POPUP_HEIGHT) / 2)

#define TEXT_GAME_OVER_WIDTH 200
#define TEXT_GAME_OVER_HEIGHT 36
#define TEXT_GAME_OVER_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_GAME_OVER_WIDTH) / 2)
#define TEXT_GAME_OVER_Y (GAME_OVER_POPUP_Y + 2)
#define TEXT_GAME_OVER_SIZE 16

#define TEXT_GAME_RESULT_WIDTH 80
#define TEXT_GAME_RESULT_HEIGHT 36
#define TEXT_GAME_RESULT_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_GAME_RESULT_WIDTH) / 2)
#define TEXT_GAME_RESULT_Y (GAME_OVER_POPUP_Y + TABLE_CELL_SIZE + 2)
#define TEXT_GAME_RESULT_SIZE 16

#define TEXT_PLAY_AGAIN_WIDTH 120
#define TEXT_PLAY_AGAIN_HEIGHT 36
#define TEXT_PLAY_AGAIN_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_PLAY_AGAIN_WIDTH) / 2)
#define TEXT_PLAY_AGAIN_Y (GAME_OVER_POPUP_Y + TABLE_CELL_SIZE * 2 + 2)
#define TEXT_PLAY_AGAIN_SIZE 16

#define YES_CELL_WIDTH TABLE_CELL_SIZE
#define YES_CELL_HEIGHT TABLE_CELL_SIZE
#define YES_CELL_X (GAME_OVER_POPUP_X + TABLE_CELL_SIZE + TABLE_CELL_SIZE/2)
#define YES_CELL_Y (GAME_OVER_POPUP_Y + TABLE_CELL_SIZE * 3 + TABLE_CELL_SIZE/2)

#define NO_CELL_WIDTH TABLE_CELL_SIZE
#define NO_CELL_HEIGHT TABLE_CELL_SIZE
#define NO_CELL_X (YES_CELL_X + TABLE_CELL_SIZE * 3)
#define NO_CELL_Y YES_CELL_Y