#pragma once
#define SDL_MAIN_HANDLED
#define TABLE_ROW 10
#define TABLE_COL 15
#define TABLE_SIZE (TABLE_ROW * TABLE_COL)
#define TABLE_CELL_SIZE 40
#define WINDOW_WIDTH (TABLE_CELL_SIZE * TABLE_COL)
#define WINDOW_HEIGHT (TABLE_CELL_SIZE * TABLE_ROW)
