#pragma once
#define SDL_MAIN_HANDLED

#define TABLE_WIDTH 9
#define TABLE_ROW 9
#define TABLE_COL 18
#define TABLE_SIZE (TABLE_ROW * TABLE_COL)
#define TABLE_CELL_SIZE 40

#define WINDOW_WIDTH (TABLE_CELL_SIZE * TABLE_COL)
#define WINDOW_HEIGHT (TABLE_CELL_SIZE * TABLE_ROW)

#define GAME_OVER_POPUP_WIDTH 7
#define GAME_OVER_POPUP_HEIGHT 5
//#define GAME_OVER_POPUP_X ((WINDOW_WIDTH - GAME_OVER_POPUP_WIDTH) / 2)
//#define GAME_OVER_POPUP_Y ((WINDOW_HEIGHT - GAME_OVER_POPUP_HEIGHT) / 2)

//Text
#define TEXT_SIZE 32

#define TEXT_GAME_OVER_WIDTH 5
#define TEXT_GAME_OVER_HEIGHT 1
//#define TEXT_GAME_OVER_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_GAME_OVER_WIDTH) / 2)
//#define TEXT_GAME_OVER_Y (GAME_OVER_POPUP_Y + 2)

#define TEXT_GAME_RESULT_WIDTH 2
#define TEXT_GAME_RESULT_HEIGHT 1
//#define TEXT_GAME_RESULT_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_GAME_RESULT_WIDTH) / 2)
//#define TEXT_GAME_RESULT_Y (GAME_OVER_POPUP_Y + TABLE_CELL_SIZE + 2)

#define TEXT_PLAY_AGAIN_WIDTH 3
#define TEXT_PLAY_AGAIN_HEIGHT 1
//#define TEXT_PLAY_AGAIN_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_PLAY_AGAIN_WIDTH) / 2)
//#define TEXT_PLAY_AGAIN_Y (GAME_OVER_POPUP_Y + TABLE_CELL_SIZE * 2 + 2)

#define YES_BUTTON_WIDTH 1
#define YES_BUTTON_HEIGHT 1
//#define YES_BUTTON_X (GAME_OVER_POPUP_X + TABLE_CELL_SIZE + TABLE_CELL_SIZE/2)
//#define YES_BUTTON_Y (GAME_OVER_POPUP_Y + TABLE_CELL_SIZE * 3 + TABLE_CELL_SIZE/2)

#define NO_BUTTON_WIDTH 1
#define NO_BUTTON_HEIGHT 1
//#define NO_BUTTON_X (YES_BUTTON_X + TABLE_CELL_SIZE * 3)
//#define NO_BUTTON_Y YES_BUTTON_Y

